# Use the official PostgreSQL image from Docker Hub
FROM postgres:16.1-alpine

# Set the environment variables for PostgreSQL
ENV POSTGRES_DB=expense_tracker
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=admin

# Expose the default PostgreSQL port
EXPOSE 5432

VOLUME /var/lib/postgresql/data

