version: '3'

services:

  postgres:
    build:
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  springboot:
    build:
      dockerfile: Dockerfile.expense-tracker
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
